Namespace Microsoft.SmallVisualBasic
    Public Enum TokenType
        Illegal
        Comment
        StringLiteral
        NumericLiteral
        DateLiteral
        [True]
        [False]
        [Nothing]
        Identifier
        [Else]
        [ElseIf]
        EndFor
        [Next]
        [EndIf]
        EndSub
        EndFunction
        [Return]
        ExitLoop
        EndWhile
        [Wend]
        [For]
        ForEach
        [Goto]
        [If]
        [In]
        [Step]
        [Sub]
        [Function]
        [Then]
        [To]
        [While]
        [And]
        Equals
        [Or]
        Dot
        Lookup
        Concatenation
        Addition
        Subtraction
        Division
        Multiplication
        LeftParens
        RightParens
        LeftBracket
        RightBracket
        LeftCurlyBracket
        RightCurlyBracket
        LessThan
        LessThanEqualTo
        GreaterThan
        GreaterThanEqualTo
        NotEqualTo
        Comma
        Colon
        SingleQuote
        DoubleQuote
        ContinueLoop
    End Enum
End Namespace
