Namespace Microsoft.SmallBasic
    Public Enum Token
        Illegal
        Comment
        StringLiteral
        NumericLiteral
        Identifier
        [Else]
        [ElseIf]
        EndFor
        [Next]
        [EndIf]
        EndSub
        EndFunction
        [Return]
        EndWhile
        [Wend]
        [For]
        [Goto]
        [If]
        [Step]
        [Sub]
        [Function]
        [Then]
        [To]
        [True]
        [While]
        [And]
        Equals
        [Or]
        Dot
        Addition
        Subtraction
        Division
        Multiplication
        LeftParens
        RightParens
        LeftBracket
        RightBracket
        LeftCurlyBracket
        RightCurlyBracket
        LessThan
        LessThanEqualTo
        GreaterThan
        GreaterThanEqualTo
        NotEqualTo
        Comma
        Colon
        SingleQuote
        DoubleQuote
    End Enum
End Namespace
