'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WpfDialogs.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.
        '''</summary>
        Friend ReadOnly Property _0() As String
            Get
                Return ResourceManager.GetString("_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.
        '''</summary>
        Friend ReadOnly Property _1() As String
            Get
                Return ResourceManager.GetString("_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.
        '''</summary>
        Friend ReadOnly Property _2() As String
            Get
                Return ResourceManager.GetString("_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend ReadOnly Property _3() As String
            Get
                Return ResourceManager.GetString("_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.
        '''</summary>
        Friend ReadOnly Property _4() As String
            Get
                Return ResourceManager.GetString("_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5.
        '''</summary>
        Friend ReadOnly Property _5() As String
            Get
                Return ResourceManager.GetString("_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 6.
        '''</summary>
        Friend ReadOnly Property _6() As String
            Get
                Return ResourceManager.GetString("_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 7.
        '''</summary>
        Friend ReadOnly Property _7() As String
            Get
                Return ResourceManager.GetString("_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 8.
        '''</summary>
        Friend ReadOnly Property _8() As String
            Get
                Return ResourceManager.GetString("_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 9.
        '''</summary>
        Friend ReadOnly Property _9() As String
            Get
                Return ResourceManager.GetString("_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All petite caps.
        '''</summary>
        Friend ReadOnly Property AllPetiteCaps() As String
            Get
                Return ResourceManager.GetString("AllPetiteCaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All small caps.
        '''</summary>
        Friend ReadOnly Property AllSmallCaps() As String
            Get
                Return ResourceManager.GetString("AllSmallCaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annotation alternates.
        '''</summary>
        Friend ReadOnly Property AnnotationAlternates() As String
            Get
                Return ResourceManager.GetString("AnnotationAlternates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capitals.
        '''</summary>
        Friend ReadOnly Property Capitals() As String
            Get
                Return ResourceManager.GetString("Capitals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Capital spacing.
        '''</summary>
        Friend ReadOnly Property CapitalSpacing() As String
            Get
                Return ResourceManager.GetString("CapitalSpacing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Case sensitive forms.
        '''</summary>
        Friend ReadOnly Property CaseSensitiveForms() As String
            Get
                Return ResourceManager.GetString("CaseSensitiveForms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contextual alternates.
        '''</summary>
        Friend ReadOnly Property ContextualAlternates() As String
            Get
                Return ResourceManager.GetString("ContextualAlternates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligatures, contextual.
        '''</summary>
        Friend ReadOnly Property ContextualLigatures() As String
            Get
                Return ResourceManager.GetString("ContextualLigatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swashes, contextual.
        '''</summary>
        Friend ReadOnly Property ContextualSwashes() As String
            Get
                Return ResourceManager.GetString("ContextualSwashes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1, 2, 3, 4, 5, 6, 7, 8 ,9, 0.
        '''</summary>
        Friend ReadOnly Property Digits() As String
            Get
                Return ResourceManager.GetString("Digits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled.
        '''</summary>
        Friend ReadOnly Property Disabled() As String
            Get
                Return ResourceManager.GetString("Disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligatures, discretionary.
        '''</summary>
        Friend ReadOnly Property DiscretionaryLigatures() As String
            Get
                Return ResourceManager.GetString("DiscretionaryLigatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to East Asian expert forms.
        '''</summary>
        Friend ReadOnly Property EastAsianExpertForms() As String
            Get
                Return ResourceManager.GetString("EastAsianExpertForms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to East Asian language.
        '''</summary>
        Friend ReadOnly Property EastAsianLanguage() As String
            Get
                Return ResourceManager.GetString("EastAsianLanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to East Asian widths.
        '''</summary>
        Friend ReadOnly Property EastAsianWidths() As String
            Get
                Return ResourceManager.GetString("EastAsianWidths", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled.
        '''</summary>
        Friend ReadOnly Property Enabled() As String
            Get
                Return ResourceManager.GetString("Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fraction.
        '''</summary>
        Friend ReadOnly Property Fraction() As String
            Get
                Return ResourceManager.GetString("Fraction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full.
        '''</summary>
        Friend ReadOnly Property Full() As String
            Get
                Return ResourceManager.GetString("Full", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Half.
        '''</summary>
        Friend ReadOnly Property Half() As String
            Get
                Return ResourceManager.GetString("Half", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Historical forms.
        '''</summary>
        Friend ReadOnly Property HistoricalForms() As String
            Get
                Return ResourceManager.GetString("HistoricalForms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligatures, historical.
        '''</summary>
        Friend ReadOnly Property HistoricalLigatures() As String
            Get
                Return ResourceManager.GetString("HistoricalLigatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hojo Kanji.
        '''</summary>
        Friend ReadOnly Property HojoKanji() As String
            Get
                Return ResourceManager.GetString("HojoKanji", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inferior.
        '''</summary>
        Friend ReadOnly Property Inferior() As String
            Get
                Return ResourceManager.GetString("Inferior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JIS-04.
        '''</summary>
        Friend ReadOnly Property Jis04() As String
            Get
                Return ResourceManager.GetString("Jis04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JIS-78.
        '''</summary>
        Friend ReadOnly Property Jis78() As String
            Get
                Return ResourceManager.GetString("Jis78", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JIS-83.
        '''</summary>
        Friend ReadOnly Property Jis83() As String
            Get
                Return ResourceManager.GetString("Jis83", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JIS-90.
        '''</summary>
        Friend ReadOnly Property Jis90() As String
            Get
                Return ResourceManager.GetString("Jis90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kerning.
        '''</summary>
        Friend ReadOnly Property Kerning() As String
            Get
                Return ResourceManager.GetString("Kerning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lining.
        '''</summary>
        Friend ReadOnly Property Lining() As String
            Get
                Return ResourceManager.GetString("Lining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mathematical Greek.
        '''</summary>
        Friend ReadOnly Property MathematicalGreek() As String
            Get
                Return ResourceManager.GetString("MathematicalGreek", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NLC Kanji.
        '''</summary>
        Friend ReadOnly Property NlcKanji() As String
            Get
                Return ResourceManager.GetString("NlcKanji", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal.
        '''</summary>
        Friend ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numeral alignment.
        '''</summary>
        Friend ReadOnly Property NumeralAlignment() As String
            Get
                Return ResourceManager.GetString("NumeralAlignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numeral style.
        '''</summary>
        Friend ReadOnly Property NumeralStyle() As String
            Get
                Return ResourceManager.GetString("NumeralStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old style.
        '''</summary>
        Friend ReadOnly Property OldStyle() As String
            Get
                Return ResourceManager.GetString("OldStyle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1/2.
        '''</summary>
        Friend ReadOnly Property OneHalf() As String
            Get
                Return ResourceManager.GetString("OneHalf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ordinal.
        '''</summary>
        Friend ReadOnly Property Ordinal() As String
            Get
                Return ResourceManager.GetString("Ordinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Petite caps.
        '''</summary>
        Friend ReadOnly Property PetiteCaps() As String
            Get
                Return ResourceManager.GetString("PetiteCaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Proportional.
        '''</summary>
        Friend ReadOnly Property Proportional() As String
            Get
                Return ResourceManager.GetString("Proportional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quarter.
        '''</summary>
        Friend ReadOnly Property Quarter() As String
            Get
                Return ResourceManager.GetString("Quarter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ruby.
        '''</summary>
        Friend ReadOnly Property Ruby() As String
            Get
                Return ResourceManager.GetString("Ruby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Simplified.
        '''</summary>
        Friend ReadOnly Property Simplified() As String
            Get
                Return ResourceManager.GetString("Simplified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (simulated).
        '''</summary>
        Friend ReadOnly Property simulated() As String
            Get
                Return ResourceManager.GetString("simulated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slashed.
        '''</summary>
        Friend ReadOnly Property Slashed() As String
            Get
                Return ResourceManager.GetString("Slashed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slashed zero.
        '''</summary>
        Friend ReadOnly Property SlashedZero() As String
            Get
                Return ResourceManager.GetString("SlashedZero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Small caps.
        '''</summary>
        Friend ReadOnly Property SmallCaps() As String
            Get
                Return ResourceManager.GetString("SmallCaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stacked.
        '''</summary>
        Friend ReadOnly Property Stacked() As String
            Get
                Return ResourceManager.GetString("Stacked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ligatures, standard.
        '''</summary>
        Friend ReadOnly Property StandardLigatures() As String
            Get
                Return ResourceManager.GetString("StandardLigatures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swashes, standard.
        '''</summary>
        Friend ReadOnly Property StandardSwashes() As String
            Get
                Return ResourceManager.GetString("StandardSwashes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic alternates.
        '''</summary>
        Friend ReadOnly Property StylisticAlternates() As String
            Get
                Return ResourceManager.GetString("StylisticAlternates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  1.
        '''</summary>
        Friend ReadOnly Property StylisticSet1() As String
            Get
                Return ResourceManager.GetString("StylisticSet1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 10.
        '''</summary>
        Friend ReadOnly Property StylisticSet10() As String
            Get
                Return ResourceManager.GetString("StylisticSet10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 11.
        '''</summary>
        Friend ReadOnly Property StylisticSet11() As String
            Get
                Return ResourceManager.GetString("StylisticSet11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 12.
        '''</summary>
        Friend ReadOnly Property StylisticSet12() As String
            Get
                Return ResourceManager.GetString("StylisticSet12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 13.
        '''</summary>
        Friend ReadOnly Property StylisticSet13() As String
            Get
                Return ResourceManager.GetString("StylisticSet13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 14.
        '''</summary>
        Friend ReadOnly Property StylisticSet14() As String
            Get
                Return ResourceManager.GetString("StylisticSet14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 15.
        '''</summary>
        Friend ReadOnly Property StylisticSet15() As String
            Get
                Return ResourceManager.GetString("StylisticSet15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 16.
        '''</summary>
        Friend ReadOnly Property StylisticSet16() As String
            Get
                Return ResourceManager.GetString("StylisticSet16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 17.
        '''</summary>
        Friend ReadOnly Property StylisticSet17() As String
            Get
                Return ResourceManager.GetString("StylisticSet17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 18.
        '''</summary>
        Friend ReadOnly Property StylisticSet18() As String
            Get
                Return ResourceManager.GetString("StylisticSet18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 19.
        '''</summary>
        Friend ReadOnly Property StylisticSet19() As String
            Get
                Return ResourceManager.GetString("StylisticSet19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  2.
        '''</summary>
        Friend ReadOnly Property StylisticSet2() As String
            Get
                Return ResourceManager.GetString("StylisticSet2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set 20.
        '''</summary>
        Friend ReadOnly Property StylisticSet20() As String
            Get
                Return ResourceManager.GetString("StylisticSet20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  3.
        '''</summary>
        Friend ReadOnly Property StylisticSet3() As String
            Get
                Return ResourceManager.GetString("StylisticSet3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  4.
        '''</summary>
        Friend ReadOnly Property StylisticSet4() As String
            Get
                Return ResourceManager.GetString("StylisticSet4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  5.
        '''</summary>
        Friend ReadOnly Property StylisticSet5() As String
            Get
                Return ResourceManager.GetString("StylisticSet5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  6.
        '''</summary>
        Friend ReadOnly Property StylisticSet6() As String
            Get
                Return ResourceManager.GetString("StylisticSet6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  7.
        '''</summary>
        Friend ReadOnly Property StylisticSet7() As String
            Get
                Return ResourceManager.GetString("StylisticSet7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  8.
        '''</summary>
        Friend ReadOnly Property StylisticSet8() As String
            Get
                Return ResourceManager.GetString("StylisticSet8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stylistic set  9.
        '''</summary>
        Friend ReadOnly Property StylisticSet9() As String
            Get
                Return ResourceManager.GetString("StylisticSet9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subscript.
        '''</summary>
        Friend ReadOnly Property Subscript() As String
            Get
                Return ResourceManager.GetString("Subscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Superscript.
        '''</summary>
        Friend ReadOnly Property Superscript() As String
            Get
                Return ResourceManager.GetString("Superscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tabular.
        '''</summary>
        Friend ReadOnly Property Tabular() As String
            Get
                Return ResourceManager.GetString("Tabular", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third.
        '''</summary>
        Friend ReadOnly Property Third() As String
            Get
                Return ResourceManager.GetString("Third", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Titling.
        '''</summary>
        Friend ReadOnly Property Titling() As String
            Get
                Return ResourceManager.GetString("Titling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traditional.
        '''</summary>
        Friend ReadOnly Property Traditional() As String
            Get
                Return ResourceManager.GetString("Traditional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traditional names.
        '''</summary>
        Friend ReadOnly Property TraditionalNames() As String
            Get
                Return ResourceManager.GetString("TraditionalNames", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unicase.
        '''</summary>
        Friend ReadOnly Property Unicase() As String
            Get
                Return ResourceManager.GetString("Unicase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Variants.
        '''</summary>
        Friend ReadOnly Property Variants() As String
            Get
                Return ResourceManager.GetString("Variants", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
