Namespace Microsoft.Nautilus.Text
    Friend NotInheritable Class Strings

        Public Const InvalidSnapshot As String = "The specified ITextSnapshot doesn't belong to the correct text buffer."
        Public Const CannotUndo As String = "Cannot undo this change."
        Public Const CannotRedo As String = "Cannot redo this change."
        Public Const TextBufferChanged As String = "Text Buffer Change"
        Public Const ReadOnlyRegionCreated As String = "Create Read Only Region"
        Public Const ReadOnlyRegionRemoved As String = "Remove Read Only Region"
        Public Const TextViewDoesNotMatch As String = "TextView does not match TextView of the EditorOperations."
        Public Const NumberToDetermineWidth As String = "88888"
        Public Const ChildElementsNotSupported As String = "We don't support child elements in Text yet."
        Public Const RangeNotValid As String = "Supplied range is not valid."
        Public Const TargetRangeNotValid As String = "Supplied target range is not valid."
        Public Const InsertNewline As String = "Insert Newline"
        Public Const InsertTab As String = "Insert Tab"
        Public Const RemovePreviousTab As String = "Remove Previous Tab"
        Public Const IndentSelection As String = "Indent Selection"
        Public Const UnindentSelection As String = "Unindent Selection"
        Public Const StopTextMerge As String = "Stop Text Merge"
        Public Const InsertText As String = "Insert Text"
        Public Const DeleteText As String = "Delete Text"
        Public Const ReplaceSelectionWith As String = "Replace Selection With "
        Public Const ReplaceText As String = "Replace Text"
        Public Const ReplaceAll As String = "Replace All"
        Public Const CutSelection As String = "Cut Selection"
        Public Const Paste As String = "Paste"
        Public Const TransposeCharacter As String = "Transpose Character"
        Public Const TransposeLine As String = "Transpose Line"
        Public Const Make As String = "Make "
        Public Const Lowercase As String = "Lowercase"
        Public Const Uppercase As String = "Uppercase"
        Public Const DeleteWordToRight As String = "Delete Word To Right"
        Public Const DeleteWordToLeft As String = "Delete Word To Left"
        Public Const DeleteCharToLeft As String = "Delete Character To Left"
        Public Const DeleteCharToRight As String = "Delete Character To Right"
        Public Const ProjectionClassifierOnlyOnProjectionBuffer As String = "The projection classifier can only operate on a ProjectionBuffer."
    End Class
End Namespace
